BEGIN;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS poi_content_versions;
DROP TABLE IF EXISTS refresh_tokens;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
COMMIT;
